// Code generated by entc, DO NOT EDIT.

package activity

const (
	// Label holds the string label denoting the activity type in the database.
	Label = "activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID          = "id"         // FieldStartedAt holds the string denoting the startedat vertex property in the database.
	FieldStartedAt   = "started_at" // FieldEndedAt holds the string denoting the endedat vertex property in the database.
	FieldEndedAt     = "ended_at"   // FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"

	// Table holds the table name of the activity in the database.
	Table = "activities"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "activities"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_owner"
)

// Columns holds all SQL columns for activity fields.
var Columns = []string{
	FieldID,
	FieldStartedAt,
	FieldEndedAt,
	FieldDescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Activity type.
var ForeignKeys = []string{
	"user_owner",
}
