// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"sloth/feature/activity"
)

type ActivityCreateResult interface {
	IsActivityCreateResult()
}

type Error interface {
	IsError()
}

type Node interface {
	IsNode()
}

type ActivityConnection struct {
	Edges []*ActivityEdge `json:"edges"`
}

type ActivityEdge struct {
	Node   *activity.Activity `json:"node"`
	Cursor string             `json:"cursor"`
}

type NotFound struct {
	Message string `json:"message"`
}

func (NotFound) IsError() {}

type ValidationError struct {
	Message string `json:"message"`
}

func (ValidationError) IsActivityCreateResult() {}
func (ValidationError) IsError()                {}
